import React, { useState, useEffect, useMemo } from 'react';
import Head from 'next/head';
import Layout from '../../components/Layout';
import BeginYourHealingJourneySection from '../../components/BeginYourHealingJourneySection';
import SEOContentSection from '../../components/SEOContentSection';
import { autoGeneratedServices } from '../data/autoGeneratedServices';
import { 
  Sparkles, 
  Leaf, 
  Activity, 
  Stethoscope, 
  ChevronDown, 
  ChevronRight,
  Phone,
  Calendar,
  MapPin,
  Clock,
  CheckCircle,
  Award,
  Users,
  Shield,
  Star,
  ArrowRight,
  X,
  Search
} from 'lucide-react';

// Format service slug into a premium display name
const formatServiceName = (slug) => {
  return slug
    .replace(/-dubai$/i, '')
    .replace(/-/g, ' ')
    .replace(/\b\w/g, (char) => char.toUpperCase());
};

// Categorize all services dynamically based on slug keywords
const categorizeSlug = (slug) => {
  const s = slug.toLowerCase();
  
  if (
    s.includes('teeth') || 
    s.includes('dental') || 
    s.includes('veneer') || 
    s.includes('root-canal') || 
    s.includes('braces') || 
    s.includes('crown') || 
    s.includes('scaling') || 
    s.includes('gum') || 
    s.includes('tooth') || 
    s.includes('smile') || 
    s.includes('denture') || 
    s.includes('composite')
  ) {
    return 'dental-dubai';
  }
  
  if (
    s.includes('ayurveda') || 
    s.includes('ayurvedic') || 
    s.includes('diet') || 
    s.includes('detox') || 
    s.includes('pcos') || 
    s.includes('panchakarma') || 
    s.includes('shirodhara') || 
    s.includes('abhyanga') || 
    s.includes('basti') || 
    s.includes('nasya') || 
    s.includes('gut-health') || 
    s.includes('allopathy')
  ) {
    return 'ayurveda-dubai';
  }
  
  if (
    s.includes('hydrafacial') || 
    s.includes('hydra-facial') || 
    s.includes('oxygeneo') || 
    s.includes('golden-elixir') || 
    s.includes('exosomes-facial') || 
    s.includes('face-prp') || 
    s === 'facial'
  ) {
    return 'facial-dubai';
  }
  
  if (
    s.includes('physiotherapy') || 
    s.includes('ultrasound') || 
    s.includes('electrotherapy') || 
    s.includes('pelvic') || 
    s.includes('scoliosis') || 
    s.includes('dry-needling') || 
    s.includes('pain') || 
    s.includes('rehab') || 
    s.includes('injury') || 
    s.includes('strain') || 
    s.includes('posture') || 
    s.includes('arthritis') || 
    s.includes('recovery') || 
    s.includes('rehabilitation') || 
    s.includes('shin-splints') || 
    s.includes('plantar-fasciitis') || 
    s.includes('shoulder') || 
    s.includes('spondylosis') || 
    s.includes('sciatica') || 
    s.includes('disc') || 
    s.includes('insomnia') || 
    s.includes('anxiety') || 
    s.includes('stress') || 
    s.includes('exercise') || 
    s.includes('massage') || 
    s.includes('shockwave') || 
    s.includes('shin')
  ) {
    return 'physiotherapy-dubai';
  }
  
  if (
    s.includes('physician') || 
    s.includes('general-med') || 
    s.includes('gastro') || 
    s.includes('allergy') || 
    s.includes('wound') || 
    s.includes('infection') || 
    s.includes('diabetes') || 
    s.includes('hypertension') || 
    s.includes('check-up') || 
    s.includes('check-ups') || 
    s.includes('examination') || 
    s.includes('asthma') || 
    s.includes('copd') || 
    s.includes('dyslipidemia') || 
    s.includes('slimming') || 
    s.includes('thyroid') || 
    s.includes('iv-drip')
  ) {
    return 'general-physician-dubai';
  }
  
  return 'aesthetic-dermatology-dubai';
};

const getServicesData = () => {
  const categoryDefinitions = [
    {
      id: 1,
      name: 'Aesthetic Dermatology',
      slug: 'aesthetic-dermatology-dubai',
      iconName: 'Sparkles',
      color: '#1a5f3f',
      description: 'Advanced skincare, laser therapies, and anti-aging treatments for radiant skin.',
      featured: true
    },
    {
      id: 2,
      name: 'Dental',
      slug: 'dental-dubai',
      iconName: 'Sparkles',
      color: '#d4a574',
      description: 'Cosmetic and restorative dental treatments for healthy, confident smiles.',
      featured: true
    },
    {
      id: 3,
      name: 'Ayurveda',
      slug: 'ayurveda-dubai',
      iconName: 'Leaf',
      color: '#1a5f3f',
      description: 'Authentic traditional Ayurvedic diagnostic treatments and wellness therapies.',
      featured: true
    },
    {
      id: 4,
      name: 'Physiotherapy',
      slug: 'physiotherapy-dubai',
      iconName: 'Activity',
      color: '#d4a574',
      description: 'Advanced orthopedic physical therapy, dry needling, and sports rehabilitation.',
      featured: true
    },
    {
      id: 5,
      name: 'General Physician',
      slug: 'general-physician-dubai',
      iconName: 'Stethoscope',
      color: '#1a5f3f',
      description: 'Primary medical care, health screenings, and chronic disease management.',
      featured: true
    },
    {
      id: 6,
      name: 'Facial',
      slug: 'facial-dubai',
      iconName: 'Sparkles',
      color: '#d4a574',
      description: 'Premium medical-grade facials, skin boosters, and rejuvenation solutions.',
      featured: true
    }
  ];

  const servicesByCategory = {};
  categoryDefinitions.forEach(cat => {
    servicesByCategory[cat.slug] = [];
  });

  autoGeneratedServices.forEach(slug => {
    const targetCategory = categorizeSlug(slug);
    if (servicesByCategory[targetCategory]) {
      servicesByCategory[targetCategory].push({
        name: formatServiceName(slug),
        slug: slug,
        description: `Professional clinical ${formatServiceName(slug).toLowerCase()} treatment.`
      });
    }
  });

  return categoryDefinitions.map(cat => ({
    ...cat,
    subcategories: (servicesByCategory[cat.slug] || []).sort((a, b) => a.name.localeCompare(b.name))
  }));
};

const iconMap = {
  Sparkles,
  Leaf,
  Activity,
  Stethoscope
};

const ServicesPage = ({ initialServicesData }) => {
  const servicesSEOContent = [
    "RamaCare Polyclinic offers a comprehensive range of medical services in Dubai, designed to address the unique health needs of our community. From specialized aesthetic treatments to holistic Ayurvedic healing, our DHA-licensed clinic in Jumeirah 1 is your trusted partner for total well-being.",
    {
      type: "heading",
      text: "Our Specialized Medical Departments"
    },
    "We have organized our services into specialized departments to ensure that you receive focused and expert care. Each department is staffed by experienced medical professionals who utilize modern techniques and evidence-based practices.",
    {
      type: "list",
      items: [
        "Aesthetic Dermatology: Enhancing your natural beauty with advanced skin and hair treatments.",
        "Dental Care: Providing complete oral health solutions from preventive to cosmetic dentistry.",
        "Ayurveda: Promoting holistic health and balance through authentic traditional therapies.",
        "Physiotherapy: Helping you recover from injuries and manage pain with personalized rehabilitation.",
        "General Medicine: Offering primary healthcare, routine checkups, and chronic disease management."
      ]
    },
    {
      type: "heading",
      text: "Personalized Care for Every Patient"
    },
    "At RamaCare Polyclinic, we believe that healthcare should be personalized. We take the time to understand your symptoms, medical history, and health goals to create a customized treatment plan that works for you. Our commitment to excellence ensures that you receive the highest standard of care in a comfortable and professional setting.",
    "Explore our full list of services and discover how we can help you achieve optimal health. Whether you need a specialist consultation or a routine health checkup, RamaCare Polyclinic is here to provide the medical excellence you deserve in Dubai."
  ];

  const [expandedCategory, setExpandedCategory] = useState(null);
  const [searchQuery, setSearchQuery] = useState('');
  const [isBookingModalOpen, setIsBookingModalOpen] = useState(false);
  const [servicesData] = useState(initialServicesData || []);

  useEffect(() => {
    if (isBookingModalOpen) {
      document.body.style.overflow = 'hidden';
    } else {
      document.body.style.overflow = 'unset';
    }
    return () => {
      document.body.style.overflow = 'unset';
    };
  }, [isBookingModalOpen]);

  // Filter services and their subcategories dynamically based on search
  const filteredServices = useMemo(() => {
    if (!searchQuery.trim()) return servicesData;
    const query = searchQuery.toLowerCase();
    
    return servicesData.map(service => {
      const matchesCategory = 
        service.name.toLowerCase().includes(query) ||
        service.description.toLowerCase().includes(query);
      
      const matchedSubcategories = service.subcategories.filter(sub => 
        sub.name.toLowerCase().includes(query)
      );

      if (matchesCategory || matchedSubcategories.length > 0) {
        return {
          ...service,
          subcategories: matchedSubcategories.length > 0 ? matchedSubcategories : service.subcategories
        };
      }
      return null;
    }).filter(Boolean);
  }, [servicesData, searchQuery]);

  const toggleCategory = (categoryId) => {
    setExpandedCategory(expandedCategory === categoryId ? null : categoryId);
  };

  const handleBookAppointment = () => {
    setIsBookingModalOpen(true);
  };

  const handleCallNow = () => {
    window.location.href = 'tel:+971566597878';
  };

  return (
    <div className="force-light bg-white min-h-screen">
      <Layout>
        <Head>
          <title key="title">Medical Services in Dubai | All Treatments & Specialties</title>
          <meta name="description" content="Explore all medical services at RamaCare Polyclinic Dubai. Ayurveda, Dental, Dermatology, Physiotherapy, General Physician, and Facial treatments with expert care." key="description" />
          <meta name="keywords" content="medical services Dubai, healthcare treatments, Ayurveda Dubai, dental care Dubai, dermatology Dubai, physiotherapy Dubai, general physician Dubai" />
        </Head>
        
        <style jsx global>{`
          .force-light {
            --background: #ffffff;
            --foreground: #171717;
          }
          .dropdown-scroll::-webkit-scrollbar {
            width: 4px;
          }
          .dropdown-scroll::-webkit-scrollbar-track {
            background: #f1f1f1;
          }
          .dropdown-scroll::-webkit-scrollbar-thumb {
            background: #cbd5e1;
            border-radius: 4px;
          }
          .dropdown-scroll::-webkit-scrollbar-thumb:hover {
            background: #94a3b8;
          }
        `}</style>

        {/* Hero Section */}
        <section className="relative bg-gradient-to-b from-[#f4f7f5] to-white py-16 md:py-24 overflow-hidden border-b border-gray-100">
          <div className="absolute top-0 right-0 w-80 h-80 bg-[#1a5f3f]/5 rounded-full blur-3xl -translate-y-12 translate-x-12"></div>
          <div className="absolute bottom-0 left-0 w-80 h-80 bg-[#d4a574]/5 rounded-full blur-3xl translate-y-12 -translate-x-12"></div>
          
          <div className="max-w-7xl mx-auto px-6 relative z-10 text-center">
            <div className="inline-flex items-center gap-2 px-4 py-2 bg-white rounded-full mb-6 border border-gray-200 shadow-sm">
              <Award className="w-4 h-4 text-[#1a5f3f]" />
              <span className="text-xs font-semibold text-[#1a5f3f] tracking-wide uppercase">DHA Licensed & Trusted Healthcare</span>
            </div>
            
            <h1 className="text-4xl md:text-6xl font-bold text-gray-900 leading-tight mb-6">
              Our <span className="text-[#1a5f3f]">Medical Departments</span> <br /> & Treatments
            </h1>
            <p className="text-lg text-gray-600 max-w-2xl mx-auto mb-10 leading-relaxed">
              Explore our wide variety of clinical specialties and personalized medical services carried out in Jumeirah 1, Dubai.
            </p>
            
            <div className="flex flex-wrap gap-4 justify-center">
              <button
                onClick={handleBookAppointment}
                className="inline-flex items-center gap-2.5 px-7 py-4 bg-[#1a5f3f] text-white rounded-xl font-semibold hover:bg-[#154b32] transition-colors shadow-md"
              >
                <Calendar className="w-5 h-5" />
                <span>Book Free Consultation</span>
              </button>
              <button
                onClick={handleCallNow}
                className="inline-flex items-center gap-2.5 px-7 py-4 bg-white text-[#1a5f3f] border border-[#1a5f3f]/25 rounded-xl font-semibold hover:bg-gray-50 transition-colors shadow-sm"
              >
                <Phone className="w-5 h-5" />
                <span>Call +971 56 659 7878</span>
              </button>
            </div>
          </div>
        </section>

        {/* Dynamic Search & Specialties Section */}
        <section className="py-16 bg-white">
          <div className="max-w-7xl mx-auto px-6">
            
            {/* Search Input Box */}
            <div className="max-w-2xl mx-auto mb-16">
              <div className="relative">
                <Search className="absolute left-4 top-1/2 transform -translate-y-1/2 w-5 h-5 text-gray-400" />
                <input
                  type="text"
                  placeholder="Search for treatments, conditions, or departments..."
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  className="w-full pl-12 pr-4 py-4 bg-gray-50 border border-gray-200 rounded-2xl text-gray-800 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-[#1a5f3f]/25 focus:border-[#1a5f3f] transition-all text-base"
                />
              </div>
              <div className="mt-4 flex flex-wrap gap-2 justify-center items-center">
                <span className="text-xs text-gray-400 font-semibold uppercase">Suggestions:</span>
                {['Skin Treatment', 'Dental Veneers', 'Panchakarma', 'Physiotherapy Cost', 'Hydra Facial'].map((tag) => (
                  <button
                    key={tag}
                    onClick={() => setSearchQuery(tag)}
                    className="text-xs px-3.5 py-1.5 bg-gray-100 text-gray-600 rounded-full hover:bg-[#1a5f3f]/10 hover:text-[#1a5f3f] transition-colors"
                  >
                    {tag}
                  </button>
                ))}
              </div>
            </div>

            {/* Department Grid */}
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
              {filteredServices.map(service => {
                const IconComponent = iconMap[service.iconName] || Sparkles;
                const isExpanded = expandedCategory === service.id;
                
                return (
                  <div 
                    key={service.id}
                    className={`bg-white rounded-3xl border border-gray-100 shadow-md hover:shadow-xl transition-all duration-300 flex flex-col justify-between overflow-hidden ${
                      isExpanded ? 'ring-2 ring-[#1a5f3f]/20' : ''
                    }`}
                  >
                    {/* Header Details */}
                    <div className="p-8">
                      <div className="flex items-center gap-4 mb-6">
                        <div className="w-12 h-12 rounded-2xl bg-gradient-to-br from-[#1a5f3f] to-[#257d54] flex items-center justify-center text-white shadow-md">
                          <IconComponent className="w-6 h-6" />
                        </div>
                        <div>
                          <h2 className="text-xl font-bold text-gray-900 leading-tight">
                            {service.name}
                          </h2>
                          <p className="text-xs font-semibold text-[#d4a574] mt-0.5 uppercase tracking-wide">
                            {service.subcategories.length} Treatments Available
                          </p>
                        </div>
                      </div>
                      
                      <p className="text-sm text-gray-500 leading-relaxed mb-6">
                        {service.description}
                      </p>
                      
                      {/* Accordion Expand/Collapse Trigger */}
                      <button
                        onClick={() => toggleCategory(service.id)}
                        className="w-full flex items-center justify-between py-3.5 px-5 bg-gray-50 hover:bg-[#1a5f3f]/5 text-[#1a5f3f] font-semibold text-xs rounded-xl tracking-wider uppercase transition-colors"
                      >
                        <span>{isExpanded ? 'Hide' : 'Explore'} Treatment List</span>
                        <ChevronDown className={`w-4 h-4 transition-transform duration-300 ${isExpanded ? 'rotate-180' : ''}`} />
                      </button>

                      {/* Sub-treatments list */}
                      {isExpanded && (
                        <div className="mt-5 max-h-[300px] overflow-y-auto dropdown-scroll border-t border-gray-100 pt-4 space-y-2.5">
                          {service.subcategories.length === 0 ? (
                            <p className="text-xs text-gray-400 italic text-center py-4">No treatments found matching your criteria</p>
                          ) : (
                            service.subcategories.map(sub => (
                              <a
                                key={sub.slug}
                                href={`/services/${sub.slug}`}
                                className="group flex items-center justify-between p-3.5 bg-gray-50 hover:bg-[#1a5f3f]/5 border border-gray-100 hover:border-[#1a5f3f]/20 rounded-xl transition-all duration-200"
                              >
                                <span className="text-xs sm:text-sm font-semibold text-gray-800 group-hover:text-[#1a5f3f] transition-colors leading-snug break-words pr-2">
                                  {sub.name}
                                </span>
                                <ChevronRight className="w-4 h-4 text-gray-400 group-hover:text-[#1a5f3f] group-hover:translate-x-0.5 transition-all flex-shrink-0" />
                              </a>
                            ))
                          )}
                        </div>
                      )}
                    </div>

                    {/* Department Quick Actions */}
                    <div className="border-t border-gray-100 px-8 py-5 bg-gray-50/50 flex justify-between items-center mt-auto">
                      <a 
                        href={`/services/${service.slug}/`}
                        className="text-xs font-bold text-gray-600 hover:text-[#1a5f3f] transition-colors flex items-center gap-1"
                      >
                        <span>Department Page</span>
                        <ArrowRight className="w-3.5 h-3.5" />
                      </a>
                      <button
                        onClick={handleBookAppointment}
                        className="text-xs font-bold text-[#1a5f3f] hover:text-[#144830] transition-colors flex items-center gap-1"
                      >
                        <span>Book Clinic Visit</span>
                      </button>
                    </div>
                  </div>
                );
              })}
            </div>

            {/* Empty Search Screen */}
            {filteredServices.length === 0 && (
              <div className="text-center py-20 bg-gray-50 rounded-3xl border border-dashed border-gray-200 max-w-xl mx-auto mt-12">
                <Search className="w-10 h-10 text-gray-400 mx-auto mb-4" />
                <h3 className="text-lg font-bold text-gray-800 mb-1">No Treatments Found</h3>
                <p className="text-sm text-gray-500">We couldn&apos;t find anything matching &quot;{searchQuery}&quot;. Please check your spelling or try another term.</p>
              </div>
            )}
          </div>
        </section>

        {/* Why Choose Us */}
        <section className="py-20 bg-gray-50 border-t border-gray-100">
          <div className="max-w-7xl mx-auto px-6">
            <div className="text-center mb-16">
              <div className="inline-flex items-center gap-2 px-4 py-2 bg-[#1a5f3f]/5 rounded-full mb-4">
                <Shield className="w-4 h-4 text-[#1a5f3f]" />
                <span className="text-xs font-semibold text-[#1a5f3f] uppercase tracking-wide">Why Choose Us</span>
              </div>
              <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-3">
                Professional Clinical Excellence in Dubai
              </h2>
              <p className="text-gray-500 max-w-2xl mx-auto text-sm sm:text-base leading-relaxed">
                RamaCare Polyclinic combines experienced DHA-licensed specialists, modern diagnostic equipment, and a patient-focused recovery approach.
              </p>
            </div>
            
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
              {[
                { title: 'DHA Licensed Facility', desc: 'Completely licensed and compliant clinic operating under Dubai Health Authority guidelines.' },
                { title: 'Experienced Specialists', desc: 'Dermatologists, Physiotherapists, Dentists, and General Physicians with 15+ years expertise.' },
                { title: 'Holistic & Medical', desc: 'Integrated medicine offering both traditional Ayurvedic therapies and modern practices.' },
                { title: 'Jumeirah 1 Location', desc: 'Centrally located and highly accessible with dedicated visitor parking facilities.' }
              ].map((f, i) => (
                <div key={i} className="bg-white rounded-2xl p-6 border border-gray-100 shadow-sm hover:shadow-md transition-shadow">
                  <div className="w-10 h-10 rounded-xl bg-[#1a5f3f]/10 text-[#1a5f3f] flex items-center justify-center mb-5 font-bold text-sm">
                    0{i+1}
                  </div>
                  <h3 className="font-bold text-gray-900 mb-2">{f.title}</h3>
                  <p className="text-xs text-gray-500 leading-relaxed">{f.desc}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Appointment CTA */}
        <section className="py-20 bg-gradient-to-br from-[#1a5f3f] to-[#257d54] text-white relative overflow-hidden">
          <div className="absolute top-0 left-0 w-full h-full bg-[radial-gradient(ellipse_at_center,rgba(255,255,255,0.08),transparent_70%)] pointer-events-none"></div>
          <div className="max-w-7xl mx-auto px-6 relative z-10 text-center">
            <h2 className="text-3xl md:text-5xl font-bold mb-6">
              Get Expert Medical Care Today
            </h2>
            <p className="text-base sm:text-lg mb-10 max-w-xl mx-auto text-gray-100/90 leading-relaxed">
              Book a consultation with our experienced clinical professionals. Our friendly reception team is here to assist you.
            </p>
            <div className="flex flex-wrap gap-4 justify-center">
              <button
                onClick={handleBookAppointment}
                className="inline-flex items-center gap-2.5 px-8 py-4 bg-white text-[#1a5f3f] rounded-xl font-bold hover:bg-gray-100 transition-colors shadow-lg"
              >
                <Calendar className="w-5 h-5" />
                <span>Request Appointment</span>
              </button>
              <button
                onClick={handleCallNow}
                className="inline-flex items-center gap-2.5 px-8 py-4 bg-white/10 text-white border border-white/20 rounded-xl font-bold hover:bg-white/20 transition-colors"
              >
                <Phone className="w-5 h-5" />
                <span>Call Clinic</span>
              </button>
            </div>
          </div>
        </section>

        {/* Booking Modal */}
        {isBookingModalOpen && (
          <div className="fixed inset-0 z-[9999] flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm">
            <div className="relative w-full max-w-4xl max-h-[90vh] overflow-y-auto bg-white rounded-3xl shadow-2xl">
              <button 
                onClick={() => setIsBookingModalOpen(false)}
                className="absolute top-4 right-4 z-10 p-2 bg-white rounded-full shadow-md hover:bg-gray-100 transition-colors"
                aria-label="Close modal"
              >
                <X className="w-6 h-6 text-gray-600" />
              </button>
              <BeginYourHealingJourneySection 
                isModal={true} 
                onClose={() => setIsBookingModalOpen(false)} 
              />
            </div>
          </div>
        )}

        {/* SEO Structured Content */}
        <SEOContentSection title="Expert Medical Services in Dubai" content={servicesSEOContent} />

        {/* Dynamic SEO Link Directory - Prevents Orphaned Pages */}
        <section className="sr-only" aria-hidden="true">
          <h2>Full List of Medical Services at RamaCare Polyclinic</h2>
          <ul>
            {autoGeneratedServices.map((slug) => (
              <li key={slug}>
                <a href={`/services/${slug}/`}>{slug.replace(/-/g, ' ')}</a>
              </li>
            ))}
          </ul>
        </section>
      </Layout>
    </div>
  );
};

export async function getStaticProps() {
  const initialServicesData = getServicesData();
  return {
    props: {
      initialServicesData,
    },
  };
}

export default ServicesPage;